CREATE TABLE `cash` (
  `stockcode` int(11) NOT NULL,
  `compcode` int(11) NOT NULL,
  `publishdate` int(11) NOT NULL,
  `begindate` int(11) NOT NULL,
  `enddate` int(11) NOT NULL,
  `reporttype` int(11) NOT NULL,
  `quarter` varchar(4) NOT NULL,
  `adjustdate` int(11) NOT NULL,
  `accstacode` int(11) NOT NULL,
  `accstaname` varchar(10) NOT NULL,
  `laborgetcash` double NOT NULL DEFAULT '0',
  `deponetr` double NOT NULL DEFAULT '0',
  `bankloannetincr` double NOT NULL DEFAULT '0',
  `fininstnetr` double NOT NULL DEFAULT '0',
  `inspremcash` double NOT NULL DEFAULT '0',
  `insnetc` double NOT NULL DEFAULT '0',
  `savinetr` double NOT NULL DEFAULT '0',
  `disptradnetincr` double NOT NULL DEFAULT '0',
  `charintecash` double NOT NULL DEFAULT '0',
  `fdsborrnetr` double NOT NULL DEFAULT '0',
  `repnetincr` double NOT NULL DEFAULT '0',
  `taxrefd` double NOT NULL DEFAULT '0',
  `receotherbizcash` double NOT NULL DEFAULT '0',
  `bizinflitse` double NOT NULL DEFAULT '0',
  `bizinflform` double NOT NULL DEFAULT '0',
  `bizcashinfl` double NOT NULL DEFAULT '0',
  `labopayc` double NOT NULL DEFAULT '0',
  `loansnetr` double NOT NULL DEFAULT '0',
  `tradepaymnetr` double NOT NULL DEFAULT '0',
  `paycompgold` double NOT NULL DEFAULT '0',
  `payintecash` double NOT NULL DEFAULT '0',
  `paydivicash` double NOT NULL DEFAULT '0',
  `payworkcash` double NOT NULL DEFAULT '0',
  `paytax` double NOT NULL DEFAULT '0',
  `payacticash` double NOT NULL DEFAULT '0',
  `bizoutfitse` double NOT NULL DEFAULT '0',
  `bizoutfform` double NOT NULL DEFAULT '0',
  `bizcashoutf` double NOT NULL DEFAULT '0',
  `biznetitse` double NOT NULL DEFAULT '0',
  `biznetform` double NOT NULL DEFAULT '0',
  `mananetr` double NOT NULL DEFAULT '0',
  `withinvgetcash` double NOT NULL DEFAULT '0',
  `inveretugetcash` double NOT NULL DEFAULT '0',
  `fixedassetnetc` double NOT NULL DEFAULT '0',
  `subsnetc` double NOT NULL DEFAULT '0',
  `receinvcash` double NOT NULL DEFAULT '0',
  `reducashpled` double NOT NULL DEFAULT '0',
  `invinflitse` double NOT NULL DEFAULT '0',
  `invinffrom` double NOT NULL DEFAULT '0',
  `invcashinfl` double NOT NULL DEFAULT '0',
  `acquassetcash` double NOT NULL DEFAULT '0',
  `invpayc` double NOT NULL DEFAULT '0',
  `loannetr` double NOT NULL DEFAULT '0',
  `subspaynetcash` double NOT NULL DEFAULT '0',
  `payinvecash` double NOT NULL DEFAULT '0',
  `incrcashpled` double NOT NULL DEFAULT '0',
  `invoutfitse` double NOT NULL DEFAULT '0',
  `invoutfform` double NOT NULL DEFAULT '0',
  `invcashoutf` double NOT NULL DEFAULT '0',
  `netinvitse` double NOT NULL DEFAULT '0',
  `netinvform` double NOT NULL DEFAULT '0',
  `invnetcashflow` double NOT NULL DEFAULT '0',
  `invrececash` double NOT NULL DEFAULT '0',
  `subsrececash` double NOT NULL DEFAULT '0',
  `recefromloan` double NOT NULL DEFAULT '0',
  `issbdrececash` double NOT NULL DEFAULT '0',
  `recefincash` double NOT NULL DEFAULT '0',
  `fininflitse` double NOT NULL DEFAULT '0',
  `fininflform` double NOT NULL DEFAULT '0',
  `fincashinfl` double NOT NULL DEFAULT '0',
  `debtpaycash` double NOT NULL DEFAULT '0',
  `diviprofpaycash` double NOT NULL DEFAULT '0',
  `subspaydivid` double NOT NULL DEFAULT '0',
  `finrelacash` double NOT NULL DEFAULT '0',
  `finoutfitse` double NOT NULL DEFAULT '0',
  `finoutfform` double NOT NULL DEFAULT '0',
  `fincashoutf` double NOT NULL DEFAULT '0',
  `finnetitse` double NOT NULL DEFAULT '0',
  `finnetform` double NOT NULL DEFAULT '0',
  `finnetcflow` double NOT NULL DEFAULT '0',
  `chgexchgchgs` double NOT NULL DEFAULT '0',
  `netcashitse` double NOT NULL DEFAULT '0',
  `netcashform` double NOT NULL DEFAULT '0',
  `cashnetr` double NOT NULL DEFAULT '0',
  `inicashbala` double NOT NULL DEFAULT '0',
  `cashfinalitse` double NOT NULL DEFAULT '0',
  `cashfinalform` double NOT NULL DEFAULT '0',
  `finalcashbala` double NOT NULL DEFAULT '0',
  `netprofit` double NOT NULL DEFAULT '0',
  `minysharrigh` double NOT NULL DEFAULT '0',
  `unreinveloss` double NOT NULL DEFAULT '0',
  `asseimpa` double NOT NULL DEFAULT '0',
  `assedepr` double NOT NULL DEFAULT '0',
  `realestadep` double NOT NULL DEFAULT '0',
  `intaasseamor` double NOT NULL DEFAULT '0',
  `longdefeexpenamor` double NOT NULL DEFAULT '0',
  `prepexpedecr` double NOT NULL DEFAULT '0',
  `accrexpeincr` double NOT NULL DEFAULT '0',
  `dispfixedassetloss` double NOT NULL DEFAULT '0',
  `fixedassescraloss` double NOT NULL DEFAULT '0',
  `valuechgloss` double NOT NULL DEFAULT '0',
  `defeincoincr` double NOT NULL DEFAULT '0',
  `estidebts` double NOT NULL DEFAULT '0',
  `finexpe` double NOT NULL DEFAULT '0',
  `inveloss` double NOT NULL DEFAULT '0',
  `defetaxassetdecr` double NOT NULL DEFAULT '0',
  `defetaxliabincr` double NOT NULL DEFAULT '0',
  `inveredu` double NOT NULL DEFAULT '0',
  `receredu` double NOT NULL DEFAULT '0',
  `payaincr` double NOT NULL DEFAULT '0',
  `unseparachg` double NOT NULL DEFAULT '0',
  `unfiparachg` double NOT NULL DEFAULT '0',
  `other` double NOT NULL DEFAULT '0',
  `biznetscheitse` double NOT NULL DEFAULT '0',
  `biznetscheform` double NOT NULL DEFAULT '0',
  `biznetcflow` double NOT NULL DEFAULT '0',
  `debtintocapi` double NOT NULL DEFAULT '0',
  `expiconvbd` double NOT NULL DEFAULT '0',
  `finfixedasset` double NOT NULL DEFAULT '0',
  `cashfinalbala` double NOT NULL DEFAULT '0',
  `cashopenbala` double NOT NULL DEFAULT '0',
  `equfinalbala` double NOT NULL DEFAULT '0',
  `equopenbala` double NOT NULL DEFAULT '0',
  `netcashscheitse` double NOT NULL DEFAULT '0',
  `netcashscheform` double NOT NULL DEFAULT '0',
  `cashneti` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`stockcode`),
  KEY `date_type_index` (`compcode`,`enddate`,`quarter`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
