 CREATE TABLE `cash` (
  `stockcode` int(11) NOT NULL,
  `compcode` int(11) NOT NULL,
  `publishdate` int(11) NOT NULL,
  `enddate` int(11) NOT NULL,
  `reporttype` int(11) NOT NULL,
  `quarter` varchar(4) NOT NULL,
  `adjustdate` int(11) NOT NULL,
  `accstacode` int(11) NOT NULL,
  `accstaname` varchar(10) NOT NULL,
  `laborgetcash` bigint(20) NOT NULL DEFAULT '0',
  `deponetr` bigint(20) NOT NULL DEFAULT '0',
  `bankloannetincr` bigint(20) NOT NULL DEFAULT '0',
  `fininstnetr` bigint(20) NOT NULL DEFAULT '0',
  `inspremcash` bigint(20) NOT NULL DEFAULT '0',
  `insnetc` bigint(20) NOT NULL DEFAULT '0',
  `savinetr` bigint(20) NOT NULL DEFAULT '0',
  `disptradnetincr` bigint(20) NOT NULL DEFAULT '0',
  `charintecash` bigint(20) NOT NULL DEFAULT '0',
  `fdsborrnetr` bigint(20) NOT NULL DEFAULT '0',
  `repnetincr` bigint(20) NOT NULL DEFAULT '0',
  `taxrefd` bigint(20) NOT NULL DEFAULT '0',
  `receotherbizcash` bigint(20) NOT NULL DEFAULT '0',
  `bizinflitse` bigint(20) NOT NULL DEFAULT '0',
  `bizinflform` bigint(20) NOT NULL DEFAULT '0',
  `bizcashinfl` bigint(20) NOT NULL DEFAULT '0',
  `labopayc` bigint(20) NOT NULL DEFAULT '0',
  `loansnetr` bigint(20) NOT NULL DEFAULT '0',
  `tradepaymnetr` bigint(20) NOT NULL DEFAULT '0',
  `paycompgold` bigint(20) NOT NULL DEFAULT '0',
  `payintecash` bigint(20) NOT NULL DEFAULT '0',
  `paydivicash` bigint(20) NOT NULL DEFAULT '0',
  `payworkcash` bigint(20) NOT NULL DEFAULT '0',
  `paytax` bigint(20) NOT NULL DEFAULT '0',
  `payacticash` bigint(20) NOT NULL DEFAULT '0',
  `bizoutfitse` bigint(20) NOT NULL DEFAULT '0',
  `bizoutfform` bigint(20) NOT NULL DEFAULT '0',
  `bizcashoutf` bigint(20) NOT NULL DEFAULT '0',
  `biznetitse` bigint(20) NOT NULL DEFAULT '0',
  `biznetform` bigint(20) NOT NULL DEFAULT '0',
  `mananetr` bigint(20) NOT NULL DEFAULT '0',
  `withinvgetcash` bigint(20) NOT NULL DEFAULT '0',
  `inveretugetcash` bigint(20) NOT NULL DEFAULT '0',
  `fixedassetnetc` bigint(20) NOT NULL DEFAULT '0',
  `subsnetc` bigint(20) NOT NULL DEFAULT '0',
  `receinvcash` bigint(20) NOT NULL DEFAULT '0',
  `reducashpled` bigint(20) NOT NULL DEFAULT '0',
  `invinflitse` bigint(20) NOT NULL DEFAULT '0',
  `invinffrom` bigint(20) NOT NULL DEFAULT '0',
  `invcashinfl` bigint(20) NOT NULL DEFAULT '0',
  `acquassetcash` bigint(20) NOT NULL DEFAULT '0',
  `invpayc` bigint(20) NOT NULL DEFAULT '0',
  `loannetr` bigint(20) NOT NULL DEFAULT '0',
  `subspaynetcash` bigint(20) NOT NULL DEFAULT '0',
  `payinvecash` bigint(20) NOT NULL DEFAULT '0',
  `incrcashpled` bigint(20) NOT NULL DEFAULT '0',
  `invoutfitse` bigint(20) NOT NULL DEFAULT '0',
  `invoutfform` bigint(20) NOT NULL DEFAULT '0',
  `invcashoutf` bigint(20) NOT NULL DEFAULT '0',
  `netinvitse` bigint(20) NOT NULL DEFAULT '0',
  `netinvform` bigint(20) NOT NULL DEFAULT '0',
  `invnetcashflow` bigint(20) NOT NULL DEFAULT '0',
  `invrececash` bigint(20) NOT NULL DEFAULT '0',
  `subsrececash` bigint(20) NOT NULL DEFAULT '0',
  `recefromloan` bigint(20) NOT NULL DEFAULT '0',
  `issbdrececash` bigint(20) NOT NULL DEFAULT '0',
  `recefincash` bigint(20) NOT NULL DEFAULT '0',
  `fininflitse` bigint(20) NOT NULL DEFAULT '0',
  `fininflform` bigint(20) NOT NULL DEFAULT '0',
  `fincashinfl` bigint(20) NOT NULL DEFAULT '0',
  `debtpaycash` bigint(20) NOT NULL DEFAULT '0',
  `diviprofpaycash` bigint(20) NOT NULL DEFAULT '0',
  `subspaydivid` bigint(20) NOT NULL DEFAULT '0',
  `finrelacash` bigint(20) NOT NULL DEFAULT '0',
  `finoutfitse` bigint(20) NOT NULL DEFAULT '0',
  `finoutfform` bigint(20) NOT NULL DEFAULT '0',
  `fincashoutf` bigint(20) NOT NULL DEFAULT '0',
  `finnetitse` bigint(20) NOT NULL DEFAULT '0',
  `finnetform` bigint(20) NOT NULL DEFAULT '0',
  `finnetcflow` bigint(20) NOT NULL DEFAULT '0',
  `chgexchgchgs` bigint(20) NOT NULL DEFAULT '0',
  `netcashitse` bigint(20) NOT NULL DEFAULT '0',
  `netcashform` bigint(20) NOT NULL DEFAULT '0',
  `cashnetr` bigint(20) NOT NULL DEFAULT '0',
  `inicashbala` bigint(20) NOT NULL DEFAULT '0',
  `cashfinalitse` bigint(20) NOT NULL DEFAULT '0',
  `cashfinalform` bigint(20) NOT NULL DEFAULT '0',
  `finalcashbala` bigint(20) NOT NULL DEFAULT '0',
  `netprofit` bigint(20) NOT NULL DEFAULT '0',
  `minysharrigh` bigint(20) NOT NULL DEFAULT '0',
  `unreinveloss` bigint(20) NOT NULL DEFAULT '0',
  `asseimpa` bigint(20) NOT NULL DEFAULT '0',
  `assedepr` bigint(20) NOT NULL DEFAULT '0',
  `realestadep` bigint(20) NOT NULL DEFAULT '0',
  `intaasseamor` bigint(20) NOT NULL DEFAULT '0',
  `longdefeexpenamor` bigint(20) NOT NULL DEFAULT '0',
  `prepexpedecr` bigint(20) NOT NULL DEFAULT '0',
  `accrexpeincr` bigint(20) NOT NULL DEFAULT '0',
  `dispfixedassetloss` bigint(20) NOT NULL DEFAULT '0',
  `fixedassescraloss` bigint(20) NOT NULL DEFAULT '0',
  `valuechgloss` bigint(20) NOT NULL DEFAULT '0',
  `defeincoincr` bigint(20) NOT NULL DEFAULT '0',
  `estidebts` bigint(20) NOT NULL DEFAULT '0',
  `finexpe` bigint(20) NOT NULL DEFAULT '0',
  `inveloss` bigint(20) NOT NULL DEFAULT '0',
  `defetaxassetdecr` bigint(20) NOT NULL DEFAULT '0',
  `defetaxliabincr` bigint(20) NOT NULL DEFAULT '0',
  `inveredu` bigint(20) NOT NULL DEFAULT '0',
  `receredu` bigint(20) NOT NULL DEFAULT '0',
  `payaincr` bigint(20) NOT NULL DEFAULT '0',
  `unseparachg` bigint(20) NOT NULL DEFAULT '0',
  `unfiparachg` bigint(20) NOT NULL DEFAULT '0',
  `other` bigint(20) NOT NULL DEFAULT '0',
  `biznetscheitse` bigint(20) NOT NULL DEFAULT '0',
  `biznetscheform` bigint(20) NOT NULL DEFAULT '0',
  `biznetcflow` bigint(20) NOT NULL DEFAULT '0',
  `debtintocapi` bigint(20) NOT NULL DEFAULT '0',
  `expiconvbd` bigint(20) NOT NULL DEFAULT '0',
  `finfixedasset` bigint(20) NOT NULL DEFAULT '0',
  `cashfinalbala` bigint(20) NOT NULL DEFAULT '0',
  `cashopenbala` bigint(20) NOT NULL DEFAULT '0',
  `equfinalbala` bigint(20) NOT NULL DEFAULT '0',
  `equopenbala` bigint(20) NOT NULL DEFAULT '0',
  `netcashscheitse` bigint(20) NOT NULL DEFAULT '0',
  `netcashscheform` bigint(20) NOT NULL DEFAULT '0',
  `cashneti` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`stockcode`),
  KEY `date_type_index` (`compcode`,`enddate`,`quarter`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
