 CREATE TABLE `finindex` (
  `stockcode` int(11) NOT NULL,
  `compcode` int(11) NOT NULL,
  `reportdate` int(11) NOT NULL,
  `quarter` varchar(4) NOT NULL,
  `basiceps` bigint(20) NOT NULL DEFAULT '0',
  `epsdiluted` bigint(20) NOT NULL DEFAULT '0',
  `epsweighted` bigint(20) NOT NULL DEFAULT '0',
  `naps` bigint(20) NOT NULL DEFAULT '0',
  `opercashpershare` bigint(20) NOT NULL DEFAULT '0',
  `peropecashpershare` bigint(20) NOT NULL DEFAULT '0',
  `netassgrowrate` bigint(20) NOT NULL DEFAULT '0',
  `dilutedroe` bigint(20) NOT NULL DEFAULT '0',
  `weightedroe` bigint(20) NOT NULL DEFAULT '0',
  `mainbusincgrowrate` bigint(20) NOT NULL DEFAULT '0',
  `netincgrowrate` bigint(20) NOT NULL DEFAULT '0',
  `totassgrowrate` bigint(20) NOT NULL DEFAULT '0',
  `salegrossprofitrto` bigint(20) NOT NULL DEFAULT '0',
  `mainbusiincome` bigint(20) NOT NULL DEFAULT '0',
  `mainbusiprofit` bigint(20) NOT NULL DEFAULT '0',
  `totprofit` bigint(20) NOT NULL DEFAULT '0',
  `netprofit` bigint(20) NOT NULL DEFAULT '0',
  `totalassets` bigint(20) NOT NULL DEFAULT '0',
  `totalliab` bigint(20) NOT NULL DEFAULT '0',
  `totsharequi` bigint(20) NOT NULL DEFAULT '0',
  `operrevenue` bigint(20) NOT NULL DEFAULT '0',
  `invnetcashflow` bigint(20) NOT NULL DEFAULT '0',
  `finnetcflow` bigint(20) NOT NULL DEFAULT '0',
  `chgexchgchgs` bigint(20) NOT NULL DEFAULT '0',
  `cashnetr` bigint(20) NOT NULL DEFAULT '0',
  `cashequfinbal` bigint(20) NOT NULL DEFAULT '0',
  `symbol` bigint(20) NOT NULL DEFAULT '0',
  `name` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`stockcode`),
  KEY `date_type_index` (`compcode`,`reportdate`,`quarter`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
