CREATE TABLE `finindex` (
  `stockcode` int(11) NOT NULL,
  `compcode` int(11) NOT NULL,
  `reportdate` int(11) NOT NULL,
  `quarter` varchar(4) NOT NULL,
  `basiceps` double NOT NULL DEFAULT '0',
  `epsdiluted` double NOT NULL DEFAULT '0',
  `epsweighted` double NOT NULL DEFAULT '0',
  `naps` double NOT NULL DEFAULT '0',
  `opercashpershare` double NOT NULL DEFAULT '0',
  `peropecashpershare` double NOT NULL DEFAULT '0',
  `netassgrowrate` double NOT NULL DEFAULT '0',
  `dilutedroe` double NOT NULL DEFAULT '0',
  `weightedroe` double NOT NULL DEFAULT '0',
  `mainbusincgrowrate` double NOT NULL DEFAULT '0',
  `netincgrowrate` double NOT NULL DEFAULT '0',
  `totassgrowrate` double NOT NULL DEFAULT '0',
  `salegrossprofitrto` double NOT NULL DEFAULT '0',
  `mainbusiincome` double NOT NULL DEFAULT '0',
  `mainbusiprofit` double NOT NULL DEFAULT '0',
  `totprofit` double NOT NULL DEFAULT '0',
  `netprofit` double NOT NULL DEFAULT '0',
  `totalassets` double NOT NULL DEFAULT '0',
  `totalliab` double NOT NULL DEFAULT '0',
  `totsharequi` double NOT NULL DEFAULT '0',
  `operrevenue` double NOT NULL DEFAULT '0',
  `invnetcashflow` double NOT NULL DEFAULT '0',
  `finnetcflow` double NOT NULL DEFAULT '0',
  `chgexchgchgs` double NOT NULL DEFAULT '0',
  `cashnetr` double NOT NULL DEFAULT '0',
  `cashequfinbal` double NOT NULL DEFAULT '0',
  `symbol` double NOT NULL DEFAULT '0',
  `name` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`stockcode`),
  KEY `date_type_index` (`compcode`,`reportdate`,`quarter`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
