CREATE TABLE `income` (
  `stockcode` int(11) NOT NULL,
  `compcode` int(11) NOT NULL,
  `publishdate` int(11) NOT NULL,
  `enddate` int(11) NOT NULL,
  `reporttype` int(11) NOT NULL,
  `quarter` varchar(4) NOT NULL,
  `adjustdate` int(11) NOT NULL,
  `accstacode` int(11) NOT NULL,
  `accstaname` varchar(10) NOT NULL,
  `biztotinco` bigint(20) NOT NULL DEFAULT '0',
  `bizinco` bigint(20) NOT NULL DEFAULT '0',
  `inteinco` bigint(20) NOT NULL DEFAULT '0',
  `earnprem` bigint(20) NOT NULL DEFAULT '0',
  `pouninco` bigint(20) NOT NULL DEFAULT '0',
  `realsale` bigint(20) NOT NULL DEFAULT '0',
  `otherbizinco` bigint(20) NOT NULL DEFAULT '0',
  `biztotincoitse` bigint(20) NOT NULL DEFAULT '0',
  `biztotincoform` bigint(20) NOT NULL DEFAULT '0',
  `biztotcost` bigint(20) NOT NULL DEFAULT '0',
  `bizcost` bigint(20) NOT NULL DEFAULT '0',
  `inteexpe` bigint(20) NOT NULL DEFAULT '0',
  `pounexpe` bigint(20) NOT NULL DEFAULT '0',
  `realsalecost` bigint(20) NOT NULL DEFAULT '0',
  `deveexpe` bigint(20) NOT NULL DEFAULT '0',
  `surrgold` bigint(20) NOT NULL DEFAULT '0',
  `compnetexpe` bigint(20) NOT NULL DEFAULT '0',
  `contress` bigint(20) NOT NULL DEFAULT '0',
  `polidiviexpe` bigint(20) NOT NULL DEFAULT '0',
  `reinexpe` bigint(20) NOT NULL DEFAULT '0',
  `otherbizcost` bigint(20) NOT NULL DEFAULT '0',
  `biztax` bigint(20) NOT NULL DEFAULT '0',
  `salesexpe` bigint(20) NOT NULL DEFAULT '0',
  `manaexpe` bigint(20) NOT NULL DEFAULT '0',
  `finexpe` bigint(20) NOT NULL DEFAULT '0',
  `asseimpaloss` bigint(20) NOT NULL DEFAULT '0',
  `biztotcostitse` bigint(20) NOT NULL DEFAULT '0',
  `biztotcostform` bigint(20) NOT NULL DEFAULT '0',
  `valuechgloss` bigint(20) NOT NULL DEFAULT '0',
  `inveinco` bigint(20) NOT NULL DEFAULT '0',
  `assoinveprof` bigint(20) NOT NULL DEFAULT '0',
  `exchggain` bigint(20) NOT NULL DEFAULT '0',
  `futuloss` bigint(20) NOT NULL DEFAULT '0',
  `custinco` bigint(20) NOT NULL DEFAULT '0',
  `subsidyincome` bigint(20) NOT NULL DEFAULT '0',
  `otherbizprof` bigint(20) NOT NULL DEFAULT '0',
  `bizprofitse` bigint(20) NOT NULL DEFAULT '0',
  `operprofform` bigint(20) NOT NULL DEFAULT '0',
  `perprofit` bigint(20) NOT NULL DEFAULT '0',
  `nonoreve` bigint(20) NOT NULL DEFAULT '0',
  `nonoexpe` bigint(20) NOT NULL DEFAULT '0',
  `noncassetsdisl` bigint(20) NOT NULL DEFAULT '0',
  `proftotitse` bigint(20) NOT NULL DEFAULT '0',
  `proftotform` bigint(20) NOT NULL DEFAULT '0',
  `totprofit` bigint(20) NOT NULL DEFAULT '0',
  `incotaxexpe` bigint(20) NOT NULL DEFAULT '0',
  `unreinveloss` bigint(20) NOT NULL DEFAULT '0',
  `netpro1itse` bigint(20) NOT NULL DEFAULT '0',
  `netpro1form` bigint(20) NOT NULL DEFAULT '0',
  `netprofit` bigint(20) NOT NULL DEFAULT '0',
  `parenetp` bigint(20) NOT NULL DEFAULT '0',
  `mergeformnetprof` bigint(20) NOT NULL DEFAULT '0',
  `minysharrigh` bigint(20) NOT NULL DEFAULT '0',
  `netpro2itse` bigint(20) NOT NULL DEFAULT '0',
  `netpro2form` bigint(20) NOT NULL DEFAULT '0',
  `basiceps` bigint(20) NOT NULL DEFAULT '0',
  `dilutedeps` bigint(20) NOT NULL DEFAULT '0',
  `othercompinco` bigint(20) NOT NULL DEFAULT '0',
  `parecompinco` bigint(20) NOT NULL DEFAULT '0',
  `minysharinco` bigint(20) NOT NULL DEFAULT '0',
  `compincoamt` bigint(20) NOT NULL DEFAULT '0',
  `parecompincoamt` bigint(20) NOT NULL DEFAULT '0',
  `minysharincoamt` bigint(20) NOT NULL DEFAULT '0',
  `earlyundiprof` bigint(20) NOT NULL DEFAULT '0',
  `undisprofredu` bigint(20) NOT NULL DEFAULT '0',
  `otherinto` bigint(20) NOT NULL DEFAULT '0',
  `otherdistprof` bigint(20) NOT NULL DEFAULT '0',
  `legalsurp` bigint(20) NOT NULL DEFAULT '0',
  `welfare` bigint(20) NOT NULL DEFAULT '0',
  `capitalreserve` bigint(20) NOT NULL DEFAULT '0',
  `staffaward` bigint(20) NOT NULL DEFAULT '0',
  `reservefund` bigint(20) NOT NULL DEFAULT '0',
  `developfund` bigint(20) NOT NULL DEFAULT '0',
  `profreturninvest` bigint(20) NOT NULL DEFAULT '0',
  `supplycurcap` bigint(20) NOT NULL DEFAULT '0',
  `avaidistshareprof` bigint(20) NOT NULL DEFAULT '0',
  `preferredskdiv` bigint(20) NOT NULL DEFAULT '0',
  `freesurplu` bigint(20) NOT NULL DEFAULT '0',
  `dealwithdivi` bigint(20) NOT NULL DEFAULT '0',
  `capitalizeddivi` bigint(20) NOT NULL DEFAULT '0',
  `undisprofit` bigint(20) NOT NULL DEFAULT '0',
  `selldepartgain` bigint(20) NOT NULL DEFAULT '0',
  `natudisasterloss` bigint(20) NOT NULL DEFAULT '0',
  `accpolicychg` bigint(20) NOT NULL DEFAULT '0',
  `accestimatechg` bigint(20) NOT NULL DEFAULT '0',
  `debtrestruloss` bigint(20) NOT NULL DEFAULT '0',
  `othersupply` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`stockcode`),
  KEY `date_type_index` (`compcode`,`enddate`,`quarter`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
